name: gene_tree

include:
  - ./compose-backend.yaml

services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: gtwebserv
    depends_on:
      memdb:
        condition: service_healthy
        required: true
        restart: false
    networks:
      - backend
